name: Android CI

on:
  push:
    branches: [ "master", "main" ]
  pull_request:
    branches: [ "master", "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # 1. چک کردن کد ها
    - uses: actions/checkout@v4

    # 2. تنظیمات جاوا (JDK 11)
    - name: Set up JDK 11
      uses: actions/setup-java@v4
      with:
        java-version: '11'
        distribution: 'temurin'

    # 3. دادن دسترسی اجرایی به گریدل
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    # 4. بیلد گرفتن
    - name: Build with Gradle
      run: ./gradlew build

    # 5. آپلود APK (اصلاح شده به v4)
    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: app-debug
        # ⚠️ توجه: اگر پروژه شما فلوتور است، مسیر زیر رو به build/app/outputs/flutter-apk/app-release.apk تغییر بدید
        path: app/build/outputs/apk/debug/app-debug.apk
